name: Web

on:
  push:
    branches: [ "main", "develop" ]
    tags: [ "v*" ]
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      APP_NAME: ethertia
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install Dependencies
        run: |
          cargo install -f wasm-bindgen-cli
          # sudo apt install binaryen   # install for wasm-opt

      - name: Run Native Storage Tests
        run: |
          set -euxo pipefail
          cargo test --no-default-features --features target_web world_meta_create_list_delete --lib
          cargo test --no-default-features --features target_web chunk_roundtrip_save_load --lib

      - name: Compile Wasm Tests (No-Run)
        run: |
          set -euxo pipefail
          cargo test --target wasm32-unknown-unknown --no-default-features --features target_web --lib --no-run

      - name: Build for WASM
        run: |
          set -euxo pipefail
          cargo build --profile web-release --target wasm32-unknown-unknown --no-default-features --features target_web --bin ethertia

          mkdir -p artifacts/wasm
          wasm-bindgen --no-typescript --out-dir artifacts/wasm --target web target/wasm32-unknown-unknown/web-release/ethertia.wasm --out-name ethertia

          cp -r assets artifacts/wasm/
          cp build/wasm/index.html artifacts/wasm/index.html
          # wasm-opt -Oz -o ./build/wasm/ethertia_opt.wasm ./build/wasm/ethertia_bg.wasm

      - name: Zip Artifact
        run: |
          mkdir -p artifacts
          zip --recurse-paths artifacts/ethertia-wasm.zip artifacts/wasm/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-artifacts
          path: |
            artifacts/ethertia-wasm.zip
          if-no-files-found: error

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       This is the release of ${APP_NAME}.
      #     draft: false
      #     prerelease: true


